* NESPOMILA

This is a public repository for NESPOMILA-related files.


** What is NESPOMILA?

The research project _New Speakers of Minority Languages_ hosted at Institute of Slavic Studies, Polish Academy of Sciences 2021--2023.


** Funding Acknowledgement

The research leading to these results has received funding from the Norwegian Financial Mechanism 2014-2021: 2020/37/K/HS2/02779.


** Licence

Unless otherwise noted, all files are released under CC BY License. 


** What's here?

This is a repository for everything related to the NESPOMILA project.


*** `data/` | `data.zip`

Data directory. Sub directories may contain a README file with additional specification of contents.


**** `csb-wiki/`

Data extracted from Kashubian Wikipedia.


**** `new-wym-corpus/`

Data dumped from New Wymysorys Corpus (project website) as of June 2023 in JSON format.


**** `questionnaire/`

Questionnaire data from NESPOMILA and pre-NESPOMILA related projects.


**** `supplemental-data/`

Contains data not generated by the NESPOMILA project.


***** `glottolog-grambank/`

Counts of case and gender features used for the /New Speakers and Language Change: Case and Gender in Wymysorys/ manuscript.


**** `transcriptions/`

Transcribed audio data. Files are in Elan .eaf format. Audio files will be archived separately (under embargo for privacy reasons -- contact Robert Borges with interest).

CSB-pilot_audio: 10.5281/zenodo.8005371
NESPOMILA_audio: 10.5281/zenodo.8005339
NSW-HVC_audio: 10.5281/zenodo.8005360


**** `TROG/`

Data from the TROG-like task.


**** `CSB-pilot-transcriptions.txt`

List of transcription files for recordings that were generated during in-person fieldwork for the pre-NESPOMILA pilot study in Kashubia, 2019. Funded by the /Uppsala Language Documentation Group/, dept. of Linguistics and Philology, Uppsala University. 


**** `NESPOMILA-transcriptions.txxt`

List of transcription files for recordings that were generated during the NESPOMILA project (2021--2023) using the Modular Remote Data Collection Toolkit.


**** `NSW-HVC-transcriptions.txt`

List of transcription files for recordings that were generated during in-person fieldwork for the /New Speakers of Wymysorys/ post-doc at Hugo Valentin Centre, Uppsala University, 2017--2019



